package com.greendao.manager;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ventilator.administrator.DATAbase.greendao.TaskEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TASK_ENTITY".
*/
public class TaskEntityDao extends AbstractDao<TaskEntity, Long> {

    public static final String TABLENAME = "TASK_ENTITY";

    /**
     * Properties of entity TaskEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UnitName = new Property(1, String.class, "unitName", false, "UNIT_NAME");
        public final static Property GasePumpNumber = new Property(2, String.class, "gasePumpNumber", false, "GASE_PUMP_NUMBER");
        public final static Property PeopleName = new Property(3, String.class, "peopleName", false, "PEOPLE_NAME");
        public final static Property _IsCompleteTask = new Property(4, boolean.class, "_IsCompleteTask", false, "__IS_COMPLETE_TASK");
        public final static Property TaskHaveGetData = new Property(5, int.class, "taskHaveGetData", false, "TASK_HAVE_GET_DATA");
        public final static Property GreateTaskTime = new Property(6, String.class, "greateTaskTime", false, "GREATE_TASK_TIME");
        public final static Property Csff = new Property(7, String.class, "csff", false, "CSFF");
        public final static Property Tffs = new Property(8, String.class, "tffs", false, "TFFS");
        public final static Property Cfmj = new Property(9, String.class, "cfmj", false, "CFMJ");
        public final static Property Ksqckmj = new Property(10, String.class, "ksqckmj", false, "KSQCKMJ");
        public final static Property Cymjx = new Property(11, String.class, "cymjx", false, "CYMJX");
        public final static Property Cymjd = new Property(12, String.class, "cymjd", false, "CYMJD");
        public final static Property Dlbb1 = new Property(13, String.class, "dlbb1", false, "DLBB1");
        public final static Property Dlbb2 = new Property(14, String.class, "dlbb2", false, "DLBB2");
        public final static Property Dybb1 = new Property(15, String.class, "dybb1", false, "DYBB1");
        public final static Property Dybb2 = new Property(16, String.class, "dybb2", false, "DYBB2");
        public final static Property Djk1 = new Property(17, String.class, "djk1", false, "DJK1");
        public final static Property Djksfxz1 = new Property(18, boolean.class, "djksfxz1", false, "DJKSFXZ1");
        public final static Property Djqblc1 = new Property(19, String.class, "djqblc1", false, "DJQBLC1");
        public final static Property Djcsff1 = new Property(20, String.class, "djcsff1", false, "DJCSFF1");
        public final static Property Djcdxl1 = new Property(21, String.class, "djcdxl1", false, "DJCDXL1");
        public final static Property Djcdfs1 = new Property(22, String.class, "djcdfs1", false, "DJCDFS1");
        public final static Property Djeddy1 = new Property(23, String.class, "djeddy1", false, "DJEDDY1");
        public final static Property Djeddl1 = new Property(24, String.class, "djeddl1", false, "DJEDDL1");
        public final static Property Djedgl1 = new Property(25, String.class, "djedgl1", false, "DJEDGL1");
        public final static Property Djedxl1 = new Property(26, String.class, "djedxl1", false, "DJEDXL1");
        public final static Property Djkzdl1 = new Property(27, String.class, "djkzdl1", false, "DJKZDL1");
        public final static Property Djkzgl1 = new Property(28, String.class, "djkzgl1", false, "DJKZGL1");
        public final static Property Djjs1 = new Property(29, String.class, "djjs1", false, "DJJS1");
        public final static Property Djwgjjdl1 = new Property(30, String.class, "djwgjjdl1", false, "DJWGJJDL1");
        public final static Property Djk2 = new Property(31, String.class, "djk2", false, "DJK2");
        public final static Property Djksfxz2 = new Property(32, boolean.class, "djksfxz2", false, "DJKSFXZ2");
        public final static Property Djqblc2 = new Property(33, String.class, "djqblc2", false, "DJQBLC2");
        public final static Property Djcsff2 = new Property(34, String.class, "djcsff2", false, "DJCSFF2");
        public final static Property Djcdxl2 = new Property(35, String.class, "djcdxl2", false, "DJCDXL2");
        public final static Property Djcdfs2 = new Property(36, String.class, "djcdfs2", false, "DJCDFS2");
        public final static Property Djeddy2 = new Property(37, String.class, "djeddy2", false, "DJEDDY2");
        public final static Property Djeddl2 = new Property(38, String.class, "djeddl2", false, "DJEDDL2");
        public final static Property Djedgl2 = new Property(39, String.class, "djedgl2", false, "DJEDGL2");
        public final static Property Djedxl2 = new Property(40, String.class, "djedxl2", false, "DJEDXL2");
        public final static Property Djkzdl2 = new Property(41, String.class, "djkzdl2", false, "DJKZDL2");
        public final static Property Djkzgl2 = new Property(42, String.class, "djkzgl2", false, "DJKZGL2");
        public final static Property Djjs2 = new Property(43, String.class, "djjs2", false, "DJJS2");
        public final static Property Djwgjjdl2 = new Property(44, String.class, "djwgjjdl2", false, "DJWGJJDL2");
        public final static Property Fs = new Property(45, String.class, "fs", false, "FS");
        public final static Property Jy = new Property(46, String.class, "jy", false, "JY");
        public final static Property Dy = new Property(47, String.class, "dy", false, "DY");
        public final static Property Cy = new Property(48, String.class, "cy", false, "CY");
        public final static Property Wd = new Property(49, String.class, "wd", false, "WD");
        public final static Property Sd = new Property(50, String.class, "sd", false, "SD");
        public final static Property Dqy = new Property(51, String.class, "dqy", false, "DQY");
        public final static Property Dj1gl = new Property(52, String.class, "dj1gl", false, "DJ1GL");
        public final static Property Dj2gl = new Property(53, String.class, "dj2gl", false, "DJ2GL");
        public final static Property Dj1xl = new Property(54, String.class, "dj1xl", false, "DJ1XL");
        public final static Property Dj2xl = new Property(55, String.class, "dj2xl", false, "DJ2XL");
        public final static Property Edzs = new Property(56, String.class, "edzs", false, "EDZS");
        public final static Property Sczs = new Property(57, String.class, "sczs", false, "SCZS");
        public final static Property Sdfs = new Property(58, boolean.class, "sdfs", false, "SDFS");
        public final static Property Sdjy = new Property(59, boolean.class, "sdjy", false, "SDJY");
        public final static Property Sdcy = new Property(60, boolean.class, "sdcy", false, "SDCY");
        public final static Property Sdwd = new Property(61, boolean.class, "sdwd", false, "SDWD");
        public final static Property Sdsd = new Property(62, boolean.class, "sdsd", false, "SDSD");
        public final static Property Sddqy = new Property(63, boolean.class, "sddqy", false, "SDDQY");
        public final static Property Sddj1gl = new Property(64, boolean.class, "sddj1gl", false, "SDDJ1GL");
        public final static Property Sddj2gl = new Property(65, boolean.class, "sddj2gl", false, "SDDJ2GL");
        public final static Property Sddj1xl = new Property(66, boolean.class, "sddj1xl", false, "SDDJ1XL");
        public final static Property Sddj2xl = new Property(67, boolean.class, "sddj2xl", false, "SDDJ2XL");
        public final static Property Sdedzs = new Property(68, boolean.class, "sdedzs", false, "SDEDZS");
        public final static Property Sdsczs = new Property(69, boolean.class, "sdsczs", false, "SDSCZS");
        public final static Property By1 = new Property(70, String.class, "by1", false, "BY1");
        public final static Property By2 = new Property(71, String.class, "by2", false, "BY2");
        public final static Property By3 = new Property(72, String.class, "by3", false, "BY3");
        public final static Property By4 = new Property(73, String.class, "by4", false, "BY4");
        public final static Property By5 = new Property(74, String.class, "by5", false, "BY5");
        public final static Property By6 = new Property(75, String.class, "by6", false, "BY6");
        public final static Property By7 = new Property(76, String.class, "by7", false, "BY7");
        public final static Property By8 = new Property(77, String.class, "by8", false, "BY8");
        public final static Property By9 = new Property(78, String.class, "by9", false, "BY9");
        public final static Property By10 = new Property(79, String.class, "by10", false, "BY10");
        public final static Property By11 = new Property(80, String.class, "by11", false, "BY11");
        public final static Property By12 = new Property(81, String.class, "by12", false, "BY12");
        public final static Property Ptgxs = new Property(82, String.class, "ptgxs", false, "PTGXS");
    }


    public TaskEntityDao(DaoConfig config) {
        super(config);
    }
    
    public TaskEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASK_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"UNIT_NAME\" TEXT," + // 1: unitName
                "\"GASE_PUMP_NUMBER\" TEXT," + // 2: gasePumpNumber
                "\"PEOPLE_NAME\" TEXT," + // 3: peopleName
                "\"__IS_COMPLETE_TASK\" INTEGER NOT NULL ," + // 4: _IsCompleteTask
                "\"TASK_HAVE_GET_DATA\" INTEGER NOT NULL ," + // 5: taskHaveGetData
                "\"GREATE_TASK_TIME\" TEXT," + // 6: greateTaskTime
                "\"CSFF\" TEXT," + // 7: csff
                "\"TFFS\" TEXT," + // 8: tffs
                "\"CFMJ\" TEXT," + // 9: cfmj
                "\"KSQCKMJ\" TEXT," + // 10: ksqckmj
                "\"CYMJX\" TEXT," + // 11: cymjx
                "\"CYMJD\" TEXT," + // 12: cymjd
                "\"DLBB1\" TEXT," + // 13: dlbb1
                "\"DLBB2\" TEXT," + // 14: dlbb2
                "\"DYBB1\" TEXT," + // 15: dybb1
                "\"DYBB2\" TEXT," + // 16: dybb2
                "\"DJK1\" TEXT," + // 17: djk1
                "\"DJKSFXZ1\" INTEGER NOT NULL ," + // 18: djksfxz1
                "\"DJQBLC1\" TEXT," + // 19: djqblc1
                "\"DJCSFF1\" TEXT," + // 20: djcsff1
                "\"DJCDXL1\" TEXT," + // 21: djcdxl1
                "\"DJCDFS1\" TEXT," + // 22: djcdfs1
                "\"DJEDDY1\" TEXT," + // 23: djeddy1
                "\"DJEDDL1\" TEXT," + // 24: djeddl1
                "\"DJEDGL1\" TEXT," + // 25: djedgl1
                "\"DJEDXL1\" TEXT," + // 26: djedxl1
                "\"DJKZDL1\" TEXT," + // 27: djkzdl1
                "\"DJKZGL1\" TEXT," + // 28: djkzgl1
                "\"DJJS1\" TEXT," + // 29: djjs1
                "\"DJWGJJDL1\" TEXT," + // 30: djwgjjdl1
                "\"DJK2\" TEXT," + // 31: djk2
                "\"DJKSFXZ2\" INTEGER NOT NULL ," + // 32: djksfxz2
                "\"DJQBLC2\" TEXT," + // 33: djqblc2
                "\"DJCSFF2\" TEXT," + // 34: djcsff2
                "\"DJCDXL2\" TEXT," + // 35: djcdxl2
                "\"DJCDFS2\" TEXT," + // 36: djcdfs2
                "\"DJEDDY2\" TEXT," + // 37: djeddy2
                "\"DJEDDL2\" TEXT," + // 38: djeddl2
                "\"DJEDGL2\" TEXT," + // 39: djedgl2
                "\"DJEDXL2\" TEXT," + // 40: djedxl2
                "\"DJKZDL2\" TEXT," + // 41: djkzdl2
                "\"DJKZGL2\" TEXT," + // 42: djkzgl2
                "\"DJJS2\" TEXT," + // 43: djjs2
                "\"DJWGJJDL2\" TEXT," + // 44: djwgjjdl2
                "\"FS\" TEXT," + // 45: fs
                "\"JY\" TEXT," + // 46: jy
                "\"DY\" TEXT," + // 47: dy
                "\"CY\" TEXT," + // 48: cy
                "\"WD\" TEXT," + // 49: wd
                "\"SD\" TEXT," + // 50: sd
                "\"DQY\" TEXT," + // 51: dqy
                "\"DJ1GL\" TEXT," + // 52: dj1gl
                "\"DJ2GL\" TEXT," + // 53: dj2gl
                "\"DJ1XL\" TEXT," + // 54: dj1xl
                "\"DJ2XL\" TEXT," + // 55: dj2xl
                "\"EDZS\" TEXT," + // 56: edzs
                "\"SCZS\" TEXT," + // 57: sczs
                "\"SDFS\" INTEGER NOT NULL ," + // 58: sdfs
                "\"SDJY\" INTEGER NOT NULL ," + // 59: sdjy
                "\"SDCY\" INTEGER NOT NULL ," + // 60: sdcy
                "\"SDWD\" INTEGER NOT NULL ," + // 61: sdwd
                "\"SDSD\" INTEGER NOT NULL ," + // 62: sdsd
                "\"SDDQY\" INTEGER NOT NULL ," + // 63: sddqy
                "\"SDDJ1GL\" INTEGER NOT NULL ," + // 64: sddj1gl
                "\"SDDJ2GL\" INTEGER NOT NULL ," + // 65: sddj2gl
                "\"SDDJ1XL\" INTEGER NOT NULL ," + // 66: sddj1xl
                "\"SDDJ2XL\" INTEGER NOT NULL ," + // 67: sddj2xl
                "\"SDEDZS\" INTEGER NOT NULL ," + // 68: sdedzs
                "\"SDSCZS\" INTEGER NOT NULL ," + // 69: sdsczs
                "\"BY1\" TEXT," + // 70: by1
                "\"BY2\" TEXT," + // 71: by2
                "\"BY3\" TEXT," + // 72: by3
                "\"BY4\" TEXT," + // 73: by4
                "\"BY5\" TEXT," + // 74: by5
                "\"BY6\" TEXT," + // 75: by6
                "\"BY7\" TEXT," + // 76: by7
                "\"BY8\" TEXT," + // 77: by8
                "\"BY9\" TEXT," + // 78: by9
                "\"BY10\" TEXT," + // 79: by10
                "\"BY11\" TEXT," + // 80: by11
                "\"BY12\" TEXT," + // 81: by12
                "\"PTGXS\" TEXT);"); // 82: ptgxs
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TaskEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String unitName = entity.getUnitName();
        if (unitName != null) {
            stmt.bindString(2, unitName);
        }
 
        String gasePumpNumber = entity.getGasePumpNumber();
        if (gasePumpNumber != null) {
            stmt.bindString(3, gasePumpNumber);
        }
 
        String peopleName = entity.getPeopleName();
        if (peopleName != null) {
            stmt.bindString(4, peopleName);
        }
        stmt.bindLong(5, entity.get_IsCompleteTask() ? 1L: 0L);
        stmt.bindLong(6, entity.getTaskHaveGetData());
 
        String greateTaskTime = entity.getGreateTaskTime();
        if (greateTaskTime != null) {
            stmt.bindString(7, greateTaskTime);
        }
 
        String csff = entity.getCsff();
        if (csff != null) {
            stmt.bindString(8, csff);
        }
 
        String tffs = entity.getTffs();
        if (tffs != null) {
            stmt.bindString(9, tffs);
        }
 
        String cfmj = entity.getCfmj();
        if (cfmj != null) {
            stmt.bindString(10, cfmj);
        }
 
        String ksqckmj = entity.getKsqckmj();
        if (ksqckmj != null) {
            stmt.bindString(11, ksqckmj);
        }
 
        String cymjx = entity.getCymjx();
        if (cymjx != null) {
            stmt.bindString(12, cymjx);
        }
 
        String cymjd = entity.getCymjd();
        if (cymjd != null) {
            stmt.bindString(13, cymjd);
        }
 
        String dlbb1 = entity.getDlbb1();
        if (dlbb1 != null) {
            stmt.bindString(14, dlbb1);
        }
 
        String dlbb2 = entity.getDlbb2();
        if (dlbb2 != null) {
            stmt.bindString(15, dlbb2);
        }
 
        String dybb1 = entity.getDybb1();
        if (dybb1 != null) {
            stmt.bindString(16, dybb1);
        }
 
        String dybb2 = entity.getDybb2();
        if (dybb2 != null) {
            stmt.bindString(17, dybb2);
        }
 
        String djk1 = entity.getDjk1();
        if (djk1 != null) {
            stmt.bindString(18, djk1);
        }
        stmt.bindLong(19, entity.getDjksfxz1() ? 1L: 0L);
 
        String djqblc1 = entity.getDjqblc1();
        if (djqblc1 != null) {
            stmt.bindString(20, djqblc1);
        }
 
        String djcsff1 = entity.getDjcsff1();
        if (djcsff1 != null) {
            stmt.bindString(21, djcsff1);
        }
 
        String djcdxl1 = entity.getDjcdxl1();
        if (djcdxl1 != null) {
            stmt.bindString(22, djcdxl1);
        }
 
        String djcdfs1 = entity.getDjcdfs1();
        if (djcdfs1 != null) {
            stmt.bindString(23, djcdfs1);
        }
 
        String djeddy1 = entity.getDjeddy1();
        if (djeddy1 != null) {
            stmt.bindString(24, djeddy1);
        }
 
        String djeddl1 = entity.getDjeddl1();
        if (djeddl1 != null) {
            stmt.bindString(25, djeddl1);
        }
 
        String djedgl1 = entity.getDjedgl1();
        if (djedgl1 != null) {
            stmt.bindString(26, djedgl1);
        }
 
        String djedxl1 = entity.getDjedxl1();
        if (djedxl1 != null) {
            stmt.bindString(27, djedxl1);
        }
 
        String djkzdl1 = entity.getDjkzdl1();
        if (djkzdl1 != null) {
            stmt.bindString(28, djkzdl1);
        }
 
        String djkzgl1 = entity.getDjkzgl1();
        if (djkzgl1 != null) {
            stmt.bindString(29, djkzgl1);
        }
 
        String djjs1 = entity.getDjjs1();
        if (djjs1 != null) {
            stmt.bindString(30, djjs1);
        }
 
        String djwgjjdl1 = entity.getDjwgjjdl1();
        if (djwgjjdl1 != null) {
            stmt.bindString(31, djwgjjdl1);
        }
 
        String djk2 = entity.getDjk2();
        if (djk2 != null) {
            stmt.bindString(32, djk2);
        }
        stmt.bindLong(33, entity.getDjksfxz2() ? 1L: 0L);
 
        String djqblc2 = entity.getDjqblc2();
        if (djqblc2 != null) {
            stmt.bindString(34, djqblc2);
        }
 
        String djcsff2 = entity.getDjcsff2();
        if (djcsff2 != null) {
            stmt.bindString(35, djcsff2);
        }
 
        String djcdxl2 = entity.getDjcdxl2();
        if (djcdxl2 != null) {
            stmt.bindString(36, djcdxl2);
        }
 
        String djcdfs2 = entity.getDjcdfs2();
        if (djcdfs2 != null) {
            stmt.bindString(37, djcdfs2);
        }
 
        String djeddy2 = entity.getDjeddy2();
        if (djeddy2 != null) {
            stmt.bindString(38, djeddy2);
        }
 
        String djeddl2 = entity.getDjeddl2();
        if (djeddl2 != null) {
            stmt.bindString(39, djeddl2);
        }
 
        String djedgl2 = entity.getDjedgl2();
        if (djedgl2 != null) {
            stmt.bindString(40, djedgl2);
        }
 
        String djedxl2 = entity.getDjedxl2();
        if (djedxl2 != null) {
            stmt.bindString(41, djedxl2);
        }
 
        String djkzdl2 = entity.getDjkzdl2();
        if (djkzdl2 != null) {
            stmt.bindString(42, djkzdl2);
        }
 
        String djkzgl2 = entity.getDjkzgl2();
        if (djkzgl2 != null) {
            stmt.bindString(43, djkzgl2);
        }
 
        String djjs2 = entity.getDjjs2();
        if (djjs2 != null) {
            stmt.bindString(44, djjs2);
        }
 
        String djwgjjdl2 = entity.getDjwgjjdl2();
        if (djwgjjdl2 != null) {
            stmt.bindString(45, djwgjjdl2);
        }
 
        String fs = entity.getFs();
        if (fs != null) {
            stmt.bindString(46, fs);
        }
 
        String jy = entity.getJy();
        if (jy != null) {
            stmt.bindString(47, jy);
        }
 
        String dy = entity.getDy();
        if (dy != null) {
            stmt.bindString(48, dy);
        }
 
        String cy = entity.getCy();
        if (cy != null) {
            stmt.bindString(49, cy);
        }
 
        String wd = entity.getWd();
        if (wd != null) {
            stmt.bindString(50, wd);
        }
 
        String sd = entity.getSd();
        if (sd != null) {
            stmt.bindString(51, sd);
        }
 
        String dqy = entity.getDqy();
        if (dqy != null) {
            stmt.bindString(52, dqy);
        }
 
        String dj1gl = entity.getDj1gl();
        if (dj1gl != null) {
            stmt.bindString(53, dj1gl);
        }
 
        String dj2gl = entity.getDj2gl();
        if (dj2gl != null) {
            stmt.bindString(54, dj2gl);
        }
 
        String dj1xl = entity.getDj1xl();
        if (dj1xl != null) {
            stmt.bindString(55, dj1xl);
        }
 
        String dj2xl = entity.getDj2xl();
        if (dj2xl != null) {
            stmt.bindString(56, dj2xl);
        }
 
        String edzs = entity.getEdzs();
        if (edzs != null) {
            stmt.bindString(57, edzs);
        }
 
        String sczs = entity.getSczs();
        if (sczs != null) {
            stmt.bindString(58, sczs);
        }
        stmt.bindLong(59, entity.getSdfs() ? 1L: 0L);
        stmt.bindLong(60, entity.getSdjy() ? 1L: 0L);
        stmt.bindLong(61, entity.getSdcy() ? 1L: 0L);
        stmt.bindLong(62, entity.getSdwd() ? 1L: 0L);
        stmt.bindLong(63, entity.getSdsd() ? 1L: 0L);
        stmt.bindLong(64, entity.getSddqy() ? 1L: 0L);
        stmt.bindLong(65, entity.getSddj1gl() ? 1L: 0L);
        stmt.bindLong(66, entity.getSddj2gl() ? 1L: 0L);
        stmt.bindLong(67, entity.getSddj1xl() ? 1L: 0L);
        stmt.bindLong(68, entity.getSddj2xl() ? 1L: 0L);
        stmt.bindLong(69, entity.getSdedzs() ? 1L: 0L);
        stmt.bindLong(70, entity.getSdsczs() ? 1L: 0L);
 
        String by1 = entity.getBy1();
        if (by1 != null) {
            stmt.bindString(71, by1);
        }
 
        String by2 = entity.getBy2();
        if (by2 != null) {
            stmt.bindString(72, by2);
        }
 
        String by3 = entity.getBy3();
        if (by3 != null) {
            stmt.bindString(73, by3);
        }
 
        String by4 = entity.getBy4();
        if (by4 != null) {
            stmt.bindString(74, by4);
        }
 
        String by5 = entity.getBy5();
        if (by5 != null) {
            stmt.bindString(75, by5);
        }
 
        String by6 = entity.getBy6();
        if (by6 != null) {
            stmt.bindString(76, by6);
        }
 
        String by7 = entity.getBy7();
        if (by7 != null) {
            stmt.bindString(77, by7);
        }
 
        String by8 = entity.getBy8();
        if (by8 != null) {
            stmt.bindString(78, by8);
        }
 
        String by9 = entity.getBy9();
        if (by9 != null) {
            stmt.bindString(79, by9);
        }
 
        String by10 = entity.getBy10();
        if (by10 != null) {
            stmt.bindString(80, by10);
        }
 
        String by11 = entity.getBy11();
        if (by11 != null) {
            stmt.bindString(81, by11);
        }
 
        String by12 = entity.getBy12();
        if (by12 != null) {
            stmt.bindString(82, by12);
        }
 
        String ptgxs = entity.getPtgxs();
        if (ptgxs != null) {
            stmt.bindString(83, ptgxs);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TaskEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String unitName = entity.getUnitName();
        if (unitName != null) {
            stmt.bindString(2, unitName);
        }
 
        String gasePumpNumber = entity.getGasePumpNumber();
        if (gasePumpNumber != null) {
            stmt.bindString(3, gasePumpNumber);
        }
 
        String peopleName = entity.getPeopleName();
        if (peopleName != null) {
            stmt.bindString(4, peopleName);
        }
        stmt.bindLong(5, entity.get_IsCompleteTask() ? 1L: 0L);
        stmt.bindLong(6, entity.getTaskHaveGetData());
 
        String greateTaskTime = entity.getGreateTaskTime();
        if (greateTaskTime != null) {
            stmt.bindString(7, greateTaskTime);
        }
 
        String csff = entity.getCsff();
        if (csff != null) {
            stmt.bindString(8, csff);
        }
 
        String tffs = entity.getTffs();
        if (tffs != null) {
            stmt.bindString(9, tffs);
        }
 
        String cfmj = entity.getCfmj();
        if (cfmj != null) {
            stmt.bindString(10, cfmj);
        }
 
        String ksqckmj = entity.getKsqckmj();
        if (ksqckmj != null) {
            stmt.bindString(11, ksqckmj);
        }
 
        String cymjx = entity.getCymjx();
        if (cymjx != null) {
            stmt.bindString(12, cymjx);
        }
 
        String cymjd = entity.getCymjd();
        if (cymjd != null) {
            stmt.bindString(13, cymjd);
        }
 
        String dlbb1 = entity.getDlbb1();
        if (dlbb1 != null) {
            stmt.bindString(14, dlbb1);
        }
 
        String dlbb2 = entity.getDlbb2();
        if (dlbb2 != null) {
            stmt.bindString(15, dlbb2);
        }
 
        String dybb1 = entity.getDybb1();
        if (dybb1 != null) {
            stmt.bindString(16, dybb1);
        }
 
        String dybb2 = entity.getDybb2();
        if (dybb2 != null) {
            stmt.bindString(17, dybb2);
        }
 
        String djk1 = entity.getDjk1();
        if (djk1 != null) {
            stmt.bindString(18, djk1);
        }
        stmt.bindLong(19, entity.getDjksfxz1() ? 1L: 0L);
 
        String djqblc1 = entity.getDjqblc1();
        if (djqblc1 != null) {
            stmt.bindString(20, djqblc1);
        }
 
        String djcsff1 = entity.getDjcsff1();
        if (djcsff1 != null) {
            stmt.bindString(21, djcsff1);
        }
 
        String djcdxl1 = entity.getDjcdxl1();
        if (djcdxl1 != null) {
            stmt.bindString(22, djcdxl1);
        }
 
        String djcdfs1 = entity.getDjcdfs1();
        if (djcdfs1 != null) {
            stmt.bindString(23, djcdfs1);
        }
 
        String djeddy1 = entity.getDjeddy1();
        if (djeddy1 != null) {
            stmt.bindString(24, djeddy1);
        }
 
        String djeddl1 = entity.getDjeddl1();
        if (djeddl1 != null) {
            stmt.bindString(25, djeddl1);
        }
 
        String djedgl1 = entity.getDjedgl1();
        if (djedgl1 != null) {
            stmt.bindString(26, djedgl1);
        }
 
        String djedxl1 = entity.getDjedxl1();
        if (djedxl1 != null) {
            stmt.bindString(27, djedxl1);
        }
 
        String djkzdl1 = entity.getDjkzdl1();
        if (djkzdl1 != null) {
            stmt.bindString(28, djkzdl1);
        }
 
        String djkzgl1 = entity.getDjkzgl1();
        if (djkzgl1 != null) {
            stmt.bindString(29, djkzgl1);
        }
 
        String djjs1 = entity.getDjjs1();
        if (djjs1 != null) {
            stmt.bindString(30, djjs1);
        }
 
        String djwgjjdl1 = entity.getDjwgjjdl1();
        if (djwgjjdl1 != null) {
            stmt.bindString(31, djwgjjdl1);
        }
 
        String djk2 = entity.getDjk2();
        if (djk2 != null) {
            stmt.bindString(32, djk2);
        }
        stmt.bindLong(33, entity.getDjksfxz2() ? 1L: 0L);
 
        String djqblc2 = entity.getDjqblc2();
        if (djqblc2 != null) {
            stmt.bindString(34, djqblc2);
        }
 
        String djcsff2 = entity.getDjcsff2();
        if (djcsff2 != null) {
            stmt.bindString(35, djcsff2);
        }
 
        String djcdxl2 = entity.getDjcdxl2();
        if (djcdxl2 != null) {
            stmt.bindString(36, djcdxl2);
        }
 
        String djcdfs2 = entity.getDjcdfs2();
        if (djcdfs2 != null) {
            stmt.bindString(37, djcdfs2);
        }
 
        String djeddy2 = entity.getDjeddy2();
        if (djeddy2 != null) {
            stmt.bindString(38, djeddy2);
        }
 
        String djeddl2 = entity.getDjeddl2();
        if (djeddl2 != null) {
            stmt.bindString(39, djeddl2);
        }
 
        String djedgl2 = entity.getDjedgl2();
        if (djedgl2 != null) {
            stmt.bindString(40, djedgl2);
        }
 
        String djedxl2 = entity.getDjedxl2();
        if (djedxl2 != null) {
            stmt.bindString(41, djedxl2);
        }
 
        String djkzdl2 = entity.getDjkzdl2();
        if (djkzdl2 != null) {
            stmt.bindString(42, djkzdl2);
        }
 
        String djkzgl2 = entity.getDjkzgl2();
        if (djkzgl2 != null) {
            stmt.bindString(43, djkzgl2);
        }
 
        String djjs2 = entity.getDjjs2();
        if (djjs2 != null) {
            stmt.bindString(44, djjs2);
        }
 
        String djwgjjdl2 = entity.getDjwgjjdl2();
        if (djwgjjdl2 != null) {
            stmt.bindString(45, djwgjjdl2);
        }
 
        String fs = entity.getFs();
        if (fs != null) {
            stmt.bindString(46, fs);
        }
 
        String jy = entity.getJy();
        if (jy != null) {
            stmt.bindString(47, jy);
        }
 
        String dy = entity.getDy();
        if (dy != null) {
            stmt.bindString(48, dy);
        }
 
        String cy = entity.getCy();
        if (cy != null) {
            stmt.bindString(49, cy);
        }
 
        String wd = entity.getWd();
        if (wd != null) {
            stmt.bindString(50, wd);
        }
 
        String sd = entity.getSd();
        if (sd != null) {
            stmt.bindString(51, sd);
        }
 
        String dqy = entity.getDqy();
        if (dqy != null) {
            stmt.bindString(52, dqy);
        }
 
        String dj1gl = entity.getDj1gl();
        if (dj1gl != null) {
            stmt.bindString(53, dj1gl);
        }
 
        String dj2gl = entity.getDj2gl();
        if (dj2gl != null) {
            stmt.bindString(54, dj2gl);
        }
 
        String dj1xl = entity.getDj1xl();
        if (dj1xl != null) {
            stmt.bindString(55, dj1xl);
        }
 
        String dj2xl = entity.getDj2xl();
        if (dj2xl != null) {
            stmt.bindString(56, dj2xl);
        }
 
        String edzs = entity.getEdzs();
        if (edzs != null) {
            stmt.bindString(57, edzs);
        }
 
        String sczs = entity.getSczs();
        if (sczs != null) {
            stmt.bindString(58, sczs);
        }
        stmt.bindLong(59, entity.getSdfs() ? 1L: 0L);
        stmt.bindLong(60, entity.getSdjy() ? 1L: 0L);
        stmt.bindLong(61, entity.getSdcy() ? 1L: 0L);
        stmt.bindLong(62, entity.getSdwd() ? 1L: 0L);
        stmt.bindLong(63, entity.getSdsd() ? 1L: 0L);
        stmt.bindLong(64, entity.getSddqy() ? 1L: 0L);
        stmt.bindLong(65, entity.getSddj1gl() ? 1L: 0L);
        stmt.bindLong(66, entity.getSddj2gl() ? 1L: 0L);
        stmt.bindLong(67, entity.getSddj1xl() ? 1L: 0L);
        stmt.bindLong(68, entity.getSddj2xl() ? 1L: 0L);
        stmt.bindLong(69, entity.getSdedzs() ? 1L: 0L);
        stmt.bindLong(70, entity.getSdsczs() ? 1L: 0L);
 
        String by1 = entity.getBy1();
        if (by1 != null) {
            stmt.bindString(71, by1);
        }
 
        String by2 = entity.getBy2();
        if (by2 != null) {
            stmt.bindString(72, by2);
        }
 
        String by3 = entity.getBy3();
        if (by3 != null) {
            stmt.bindString(73, by3);
        }
 
        String by4 = entity.getBy4();
        if (by4 != null) {
            stmt.bindString(74, by4);
        }
 
        String by5 = entity.getBy5();
        if (by5 != null) {
            stmt.bindString(75, by5);
        }
 
        String by6 = entity.getBy6();
        if (by6 != null) {
            stmt.bindString(76, by6);
        }
 
        String by7 = entity.getBy7();
        if (by7 != null) {
            stmt.bindString(77, by7);
        }
 
        String by8 = entity.getBy8();
        if (by8 != null) {
            stmt.bindString(78, by8);
        }
 
        String by9 = entity.getBy9();
        if (by9 != null) {
            stmt.bindString(79, by9);
        }
 
        String by10 = entity.getBy10();
        if (by10 != null) {
            stmt.bindString(80, by10);
        }
 
        String by11 = entity.getBy11();
        if (by11 != null) {
            stmt.bindString(81, by11);
        }
 
        String by12 = entity.getBy12();
        if (by12 != null) {
            stmt.bindString(82, by12);
        }
 
        String ptgxs = entity.getPtgxs();
        if (ptgxs != null) {
            stmt.bindString(83, ptgxs);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TaskEntity readEntity(Cursor cursor, int offset) {
        TaskEntity entity = new TaskEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // unitName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // gasePumpNumber
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // peopleName
            cursor.getShort(offset + 4) != 0, // _IsCompleteTask
            cursor.getInt(offset + 5), // taskHaveGetData
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // greateTaskTime
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // csff
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // tffs
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // cfmj
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // ksqckmj
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // cymjx
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // cymjd
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // dlbb1
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // dlbb2
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // dybb1
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // dybb2
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // djk1
            cursor.getShort(offset + 18) != 0, // djksfxz1
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // djqblc1
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // djcsff1
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // djcdxl1
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // djcdfs1
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // djeddy1
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // djeddl1
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // djedgl1
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // djedxl1
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // djkzdl1
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // djkzgl1
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // djjs1
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // djwgjjdl1
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // djk2
            cursor.getShort(offset + 32) != 0, // djksfxz2
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // djqblc2
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // djcsff2
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // djcdxl2
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // djcdfs2
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // djeddy2
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // djeddl2
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // djedgl2
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // djedxl2
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // djkzdl2
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // djkzgl2
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // djjs2
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // djwgjjdl2
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // fs
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // jy
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // dy
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48), // cy
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // wd
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // sd
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // dqy
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // dj1gl
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53), // dj2gl
            cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54), // dj1xl
            cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55), // dj2xl
            cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56), // edzs
            cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57), // sczs
            cursor.getShort(offset + 58) != 0, // sdfs
            cursor.getShort(offset + 59) != 0, // sdjy
            cursor.getShort(offset + 60) != 0, // sdcy
            cursor.getShort(offset + 61) != 0, // sdwd
            cursor.getShort(offset + 62) != 0, // sdsd
            cursor.getShort(offset + 63) != 0, // sddqy
            cursor.getShort(offset + 64) != 0, // sddj1gl
            cursor.getShort(offset + 65) != 0, // sddj2gl
            cursor.getShort(offset + 66) != 0, // sddj1xl
            cursor.getShort(offset + 67) != 0, // sddj2xl
            cursor.getShort(offset + 68) != 0, // sdedzs
            cursor.getShort(offset + 69) != 0, // sdsczs
            cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70), // by1
            cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71), // by2
            cursor.isNull(offset + 72) ? null : cursor.getString(offset + 72), // by3
            cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73), // by4
            cursor.isNull(offset + 74) ? null : cursor.getString(offset + 74), // by5
            cursor.isNull(offset + 75) ? null : cursor.getString(offset + 75), // by6
            cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76), // by7
            cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77), // by8
            cursor.isNull(offset + 78) ? null : cursor.getString(offset + 78), // by9
            cursor.isNull(offset + 79) ? null : cursor.getString(offset + 79), // by10
            cursor.isNull(offset + 80) ? null : cursor.getString(offset + 80), // by11
            cursor.isNull(offset + 81) ? null : cursor.getString(offset + 81), // by12
            cursor.isNull(offset + 82) ? null : cursor.getString(offset + 82) // ptgxs
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TaskEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUnitName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGasePumpNumber(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPeopleName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.set_IsCompleteTask(cursor.getShort(offset + 4) != 0);
        entity.setTaskHaveGetData(cursor.getInt(offset + 5));
        entity.setGreateTaskTime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCsff(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setTffs(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCfmj(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setKsqckmj(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setCymjx(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setCymjd(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setDlbb1(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setDlbb2(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setDybb1(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setDybb2(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setDjk1(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setDjksfxz1(cursor.getShort(offset + 18) != 0);
        entity.setDjqblc1(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setDjcsff1(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setDjcdxl1(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setDjcdfs1(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setDjeddy1(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setDjeddl1(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setDjedgl1(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setDjedxl1(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setDjkzdl1(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setDjkzgl1(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setDjjs1(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setDjwgjjdl1(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setDjk2(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setDjksfxz2(cursor.getShort(offset + 32) != 0);
        entity.setDjqblc2(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setDjcsff2(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setDjcdxl2(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setDjcdfs2(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setDjeddy2(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setDjeddl2(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setDjedgl2(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setDjedxl2(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setDjkzdl2(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setDjkzgl2(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setDjjs2(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setDjwgjjdl2(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setFs(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setJy(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setDy(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setCy(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setWd(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setSd(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setDqy(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setDj1gl(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setDj2gl(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
        entity.setDj1xl(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setDj2xl(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setEdzs(cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56));
        entity.setSczs(cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57));
        entity.setSdfs(cursor.getShort(offset + 58) != 0);
        entity.setSdjy(cursor.getShort(offset + 59) != 0);
        entity.setSdcy(cursor.getShort(offset + 60) != 0);
        entity.setSdwd(cursor.getShort(offset + 61) != 0);
        entity.setSdsd(cursor.getShort(offset + 62) != 0);
        entity.setSddqy(cursor.getShort(offset + 63) != 0);
        entity.setSddj1gl(cursor.getShort(offset + 64) != 0);
        entity.setSddj2gl(cursor.getShort(offset + 65) != 0);
        entity.setSddj1xl(cursor.getShort(offset + 66) != 0);
        entity.setSddj2xl(cursor.getShort(offset + 67) != 0);
        entity.setSdedzs(cursor.getShort(offset + 68) != 0);
        entity.setSdsczs(cursor.getShort(offset + 69) != 0);
        entity.setBy1(cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70));
        entity.setBy2(cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71));
        entity.setBy3(cursor.isNull(offset + 72) ? null : cursor.getString(offset + 72));
        entity.setBy4(cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73));
        entity.setBy5(cursor.isNull(offset + 74) ? null : cursor.getString(offset + 74));
        entity.setBy6(cursor.isNull(offset + 75) ? null : cursor.getString(offset + 75));
        entity.setBy7(cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76));
        entity.setBy8(cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77));
        entity.setBy9(cursor.isNull(offset + 78) ? null : cursor.getString(offset + 78));
        entity.setBy10(cursor.isNull(offset + 79) ? null : cursor.getString(offset + 79));
        entity.setBy11(cursor.isNull(offset + 80) ? null : cursor.getString(offset + 80));
        entity.setBy12(cursor.isNull(offset + 81) ? null : cursor.getString(offset + 81));
        entity.setPtgxs(cursor.isNull(offset + 82) ? null : cursor.getString(offset + 82));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TaskEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TaskEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TaskEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
